# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow checks out code, builds an image, performs a container image
# vulnerability scan with Anchore's Grype tool, and integrates the results with GitHub
# Advanced Security code scanning feature.  For more information on the Anchore scan
# action usage and parameters, see https://github.com/anchore/scan-action. For more
# information on Anchore's container image scanning tool Grype, see
# https://github.com/anchore/grype
name: Anchore Grype vulnerability scan

on:
  push:
    branches: ["next", "main", "qa"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["next"]
  schedule:
    - cron: '42 13 * * 3'

permissions:
  contents: read

jobs:
  #Build-package:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Check out the code
  #      uses: actions/checkout@v4
  #    - name: Setup pixi
  #      uses: prefix-dev/setup-pixi@v0.9.5
  #      with:
  #        manifest-path: pyproject.toml
  #    - name: Build conda package
  #      run: |
  #        pixi run conda-build
  #        mkdir -p /tmp/local-channel/linux-64
  #        cp *.conda /tmp/local-channel/linux-64

  Anchore-Build-Scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      # only required for a private repository by github/codeql-action/upload-sarif
      # to get the Action run status
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.9.5
        with:
          manifest-path: pyproject.toml
      - name: Build conda package
        run: |
          pixi run conda-build
          mkdir -p /tmp/local-channel/linux-64
          cp *.conda /tmp/local-channel/linux-64
          ls /tmp/local-channel/linux-64
      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: indexer
          init-shell: bash
          create-args: >-
            -c conda-forge
            conda-build
            conda-index
      - name: Debug micromamba
        run: env | grep -i conda
      - name: Index local package
        run: |
          micromamba run -n indexer python -m conda_index /tmp/local-channel/
      - name: Install package
        run:
          micromamba create -n test -c /tmp/local-channel/ -c mantid-ornl/label/rc -c mantid vnext
      - name: Run the Anchore Grype scan action
        uses: anchore/scan-action@v7
        id: scan
        with:
          path: ".pixi/envs/installtest"
          fail-build: true
          severity-cutoff: critical
      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v4
        if: ${{ success() || failure() }} # if the previous step ran
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      - name: Inspect action SARIF report
        if: ${{ runner.debug == true }}
        run: cat ${{ steps.scan.outputs.sarif }}
